### ISSUE TITLE
Figma designing

### ISSUE THREAD

**Issue by treva556** [treva556/mazingira#7]
- [x]  Signups pages
- [x]  Login pages
- [x]  Donor's dashboard
- [x]  Organisations' dashboard

**Comment by stephen-nene** [comment]
[link-to-figma-design](https://www.figma.com/file/n7Tx2BCjqqSTGzKK6F5Bl1/MAZINGIRA?node-id=0%3A1&t=96XC6j1TgncOyVSF-1)
